# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/runtime-7.22.5" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.22.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.22.5.tgz";
        sha512 = "ecjvYlnAaZ/KVneE/OdKYBYfgXV3Ptu6zQWmgEF7vwKhQnvVS6bjMD2XYgj+SNvQ1GfK/pjgokfPkC/2CO8CuA==";
      };
    };
    "@novnc/novnc-1.4.0" = {
      name = "_at_novnc_slash_novnc";
      packageName = "@novnc/novnc";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@novnc/novnc/-/novnc-1.4.0.tgz";
        sha512 = "kW6ALMc5BuH08e/ond/I1naYcfjc19JYMN1EdtmgjjjzPGCjW8fMtVM3MwM6q7YLRjPlQ3orEvoKMgSS7RkEVQ==";
      };
    };
    "@patternfly/patternfly-5.0.0-alpha.43" = {
      name = "_at_patternfly_slash_patternfly";
      packageName = "@patternfly/patternfly";
      version = "5.0.0-alpha.43";
      src = fetchurl {
        url = "https://registry.npmjs.org/@patternfly/patternfly/-/patternfly-5.0.0-alpha.43.tgz";
        sha512 = "O3tOXGTxNbR8AOAiJUIth/0MAiKniTvM2L//lDisRXst0fP43I7/p0Ba3hU3ECAfMf4MsIe9tt5ZhO5Hz9lpZg==";
      };
    };
    "@patternfly/react-console-5.0.0-alpha.2" = {
      name = "_at_patternfly_slash_react-console";
      packageName = "@patternfly/react-console";
      version = "5.0.0-alpha.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@patternfly/react-console/-/react-console-5.0.0-alpha.2.tgz";
        sha512 = "D7NyvAIZXmnRKNzn07FqHfJHX0haE430yEQK7GyyMGJzq7HPIKS7ThoqVCuoeD32dBf8zPaIw+F9UDyHWSu97Q==";
      };
    };
    "@patternfly/react-core-5.0.0-alpha.83" = {
      name = "_at_patternfly_slash_react-core";
      packageName = "@patternfly/react-core";
      version = "5.0.0-alpha.83";
      src = fetchurl {
        url = "https://registry.npmjs.org/@patternfly/react-core/-/react-core-5.0.0-alpha.83.tgz";
        sha512 = "z2Erly7inGlRXgrJ79AmvQy7JfzqOLKoen+V6ko8zaIQWAluxZdgZppw/PX5fyj3Hi55sBN/GsDV8fD+o/LxbA==";
      };
    };
    "@patternfly/react-core-5.0.0-prerelease.7" = {
      name = "_at_patternfly_slash_react-core";
      packageName = "@patternfly/react-core";
      version = "5.0.0-prerelease.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@patternfly/react-core/-/react-core-5.0.0-prerelease.7.tgz";
        sha512 = "gCFKI7T2vTtogjMtyrYzHfPpC7KWNOcaa3nw5NKx3VVIcCEmf+Hp5XmIX8eDlElmIAQltRD/Q6vEtgXNh4QgcA==";
      };
    };
    "@patternfly/react-icons-5.0.0-alpha.12" = {
      name = "_at_patternfly_slash_react-icons";
      packageName = "@patternfly/react-icons";
      version = "5.0.0-alpha.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@patternfly/react-icons/-/react-icons-5.0.0-alpha.12.tgz";
        sha512 = "VwCGlB+JtpsjHJtqCcfy+CpaE+rAY2si7cd4ufJouybkoBPve/6wuTPA3K3eGtgn5cAIr18IF1Pkfkp2lR18sg==";
      };
    };
    "@patternfly/react-icons-5.0.0-prerelease.7" = {
      name = "_at_patternfly_slash_react-icons";
      packageName = "@patternfly/react-icons";
      version = "5.0.0-prerelease.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@patternfly/react-icons/-/react-icons-5.0.0-prerelease.7.tgz";
        sha512 = "nR4kv5pKN9csN6uZ/0HZg55ZM9S2ngpCL8s/pAc1PtwdOpvm5fUEb3HnCKJmf2pjRxPr7FKIF3aAAAGRd1ORIA==";
      };
    };
    "@patternfly/react-styles-5.0.0-alpha.8" = {
      name = "_at_patternfly_slash_react-styles";
      packageName = "@patternfly/react-styles";
      version = "5.0.0-alpha.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@patternfly/react-styles/-/react-styles-5.0.0-alpha.8.tgz";
        sha512 = "V/jhoKp6pz3c+2N1Yi/Ez/EJIHKEHe4SSCzF5ocGpOfaYlQpDGdttKIF0GSWksXlShYZJ5heKfARuESK9XjqRA==";
      };
    };
    "@patternfly/react-styles-5.0.0-prerelease.2" = {
      name = "_at_patternfly_slash_react-styles";
      packageName = "@patternfly/react-styles";
      version = "5.0.0-prerelease.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@patternfly/react-styles/-/react-styles-5.0.0-prerelease.2.tgz";
        sha512 = "IP/E6fHQn6qHKD+B8LDc6GyNNcSv57JsRTDvoG8rL6Ju9V4DGnEfV4M5xxUHbJ3GRWa5XSiA1ErsM4ntP100CQ==";
      };
    };
    "@patternfly/react-table-5.0.0-alpha.85" = {
      name = "_at_patternfly_slash_react-table";
      packageName = "@patternfly/react-table";
      version = "5.0.0-alpha.85";
      src = fetchurl {
        url = "https://registry.npmjs.org/@patternfly/react-table/-/react-table-5.0.0-alpha.85.tgz";
        sha512 = "rFpHkEwWstAMt4qg7YTWHYODb/NeySSaMhIWdAspvtWVU+hWkD02ejQ0eIlHSghLLKqXNsxICS1TcyDLShuyvw==";
      };
    };
    "@patternfly/react-tokens-5.0.0-prerelease.5" = {
      name = "_at_patternfly_slash_react-tokens";
      packageName = "@patternfly/react-tokens";
      version = "5.0.0-prerelease.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@patternfly/react-tokens/-/react-tokens-5.0.0-prerelease.5.tgz";
        sha512 = "36iQ7CuYh3OKf+TEZNSfU5Mpgi+aLJoFFA2V4YDaOL8+7RC8sFqh/dW3S9ThkjQrtc0fF7OK7mrPJzK+nQB9UQ==";
      };
    };
    "@spice-project/spice-html5-0.2.1" = {
      name = "_at_spice-project_slash_spice-html5";
      packageName = "@spice-project/spice-html5";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@spice-project/spice-html5/-/spice-html5-0.2.1.tgz";
        sha512 = "NY86i+x/0ldKK89enXghsXCzWwfb5DQ91hQFu9hbyLcAfCVn+ZKoYsw7xUWX6/HQBRrdu/4F1id7SdOwNqpG9g==";
      };
    };
    "attr-accept-2.2.2" = {
      name = "attr-accept";
      packageName = "attr-accept";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/attr-accept/-/attr-accept-2.2.2.tgz";
        sha512 = "7prDjvt9HmqiZ0cl5CRjtS84sEyhsHP2coDkaZKRKVfCDo9s7iw7ChVmar78Gu9pC4SoR/28wFu/G5JJhTnqEg==";
      };
    };
    "available-typed-arrays-1.0.5" = {
      name = "available-typed-arrays";
      packageName = "available-typed-arrays";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/available-typed-arrays/-/available-typed-arrays-1.0.5.tgz";
        sha512 = "DMD0KiN46eipeziST1LPP/STfDU0sufISXmjSgvVsoU2tqxctQeASejWcfNtxYKqETM1UxQ8sp2OrSBWpHY6sw==";
      };
    };
    "call-bind-1.0.2" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.2.tgz";
        sha512 = "7O+FbCihrB5WGbFYesctwmTKae6rOiIzmz1icreWJ+0aA7LJfuqhEso2T9ncpcFtzMQtzXf2QGGueWJGTYsqrA==";
      };
    };
    "date-fns-2.28.0" = {
      name = "date-fns";
      packageName = "date-fns";
      version = "2.28.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/date-fns/-/date-fns-2.28.0.tgz";
        sha512 = "8d35hViGYx/QH0icHYCeLmsLmMUheMmTyV9Fcm6gvNwdw31yXXH+O85sOBJ+OLnLQMKZowvpKb6FgMIQjcpvQw==";
      };
    };
    "deep-equal-2.0.5" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-2.0.5.tgz";
        sha512 = "nPiRgmbAtm1a3JsnLCf6/SLfXcjyN5v8L1TXzdCmHrXJ4hx+gW/w1YCcn7z8gJtSiDArZCgYtbao3QqLm/N1Sw==";
      };
    };
    "define-properties-1.2.0" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.2.0.tgz";
        sha512 = "xvqAVKGfT1+UAvPwKTVw/njhdQ8ZhXK4lI0bCIuCMrp2up9nPnaDftrLtmpTazqd1o+UY4zgzU+avtMbDP+ldA==";
      };
    };
    "es-get-iterator-1.1.3" = {
      name = "es-get-iterator";
      packageName = "es-get-iterator";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-get-iterator/-/es-get-iterator-1.1.3.tgz";
        sha512 = "sPZmqHBe6JIiTfN5q2pEi//TwxmAFHwj/XEuYjTuse78i8KxaqMTTzxPoFKuzRpDpTJ+0NAbpfenkmH2rePtuw==";
      };
    };
    "file-saver-1.3.8" = {
      name = "file-saver";
      packageName = "file-saver";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-saver/-/file-saver-1.3.8.tgz";
        sha512 = "spKHSBQIxxS81N/O21WmuXA2F6wppUCsutpzenOeZzOCCJ5gEfcbqJP983IrpLXzYmXnMUa6J03SubcNPdKrlg==";
      };
    };
    "file-selector-0.6.0" = {
      name = "file-selector";
      packageName = "file-selector";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-selector/-/file-selector-0.6.0.tgz";
        sha512 = "QlZ5yJC0VxHxQQsQhXvBaC7VRJ2uaxTf+Tfpu4Z/OcVQJVpZO+DGU0rkoVW5ce2SccxugvpBJoMvUs59iILYdw==";
      };
    };
    "focus-trap-7.4.0" = {
      name = "focus-trap";
      packageName = "focus-trap";
      version = "7.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/focus-trap/-/focus-trap-7.4.0.tgz";
        sha512 = "yI7FwUqU4TVb+7t6PaQ3spT/42r/KLEi8mtdGoQo2li/kFzmu9URmalTvw7xCCJtSOyhBxscvEAmvjeN9iHARg==";
      };
    };
    "focus-trap-7.4.3" = {
      name = "focus-trap";
      packageName = "focus-trap";
      version = "7.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/focus-trap/-/focus-trap-7.4.3.tgz";
        sha512 = "BgSSbK4GPnS2VbtZ50VtOv1Sti6DIkj3+LkVjiWMNjLeAp1SH1UlLx3ULu/DCu4vq5R4/uvTm+zrvsMsuYmGLg==";
      };
    };
    "for-each-0.3.3" = {
      name = "for-each";
      packageName = "for-each";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-each/-/for-each-0.3.3.tgz";
        sha512 = "jqYfLp7mo9vIyQf8ykW2v7A+2N4QjeCeI5+Dz9XraiO1ign81wjiH7Fb9vSOWvQfNtmSa4H2RoQTrrXivdUZmw==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "functions-have-names-1.2.3" = {
      name = "functions-have-names";
      packageName = "functions-have-names";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/functions-have-names/-/functions-have-names-1.2.3.tgz";
        sha512 = "xckBUXyTIqT97tq2x2AMb+g163b5JFysYk0x4qxNFwbfQkmNZoiRHb6sPzI9/QV33WeuvVYBUIiD4NzNIyqaRQ==";
      };
    };
    "get-intrinsic-1.2.1" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.2.1.tgz";
        sha512 = "2DcsyfABl+gVHEfCOaTrWgyt+tb6MSEGmKq+kI5HwLbIYgjgmMcV8KQ41uaKz1xxUcn9tJtgFbQUEVcEbd0FYw==";
      };
    };
    "gopd-1.0.1" = {
      name = "gopd";
      packageName = "gopd";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/gopd/-/gopd-1.0.1.tgz";
        sha512 = "d65bNlIadxvpb/A2abVdlqKqV563juRnZ1Wtk6s1sIR8uNsXR70xqIzVqxVf1eTqDunwT2MkczEeaezCKTZhwA==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-bigints-1.0.2" = {
      name = "has-bigints";
      packageName = "has-bigints";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-bigints/-/has-bigints-1.0.2.tgz";
        sha512 = "tSvCKtBr9lkF0Ex0aQiP9N+OpV4zi2r/Nee5VkRDbaqv35RLYMzbwQfFSZZH0kR+Rd6302UJZ2p/bJCEoR3VoQ==";
      };
    };
    "has-property-descriptors-1.0.0" = {
      name = "has-property-descriptors";
      packageName = "has-property-descriptors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-property-descriptors/-/has-property-descriptors-1.0.0.tgz";
        sha512 = "62DVLZGoiEBDHQyqG4w9xCuZ7eJEwNmJRWw2VY84Oedb7WFcA27fiEVe8oUQx9hAUJ4ekurquucTGwsyO1XGdQ==";
      };
    };
    "has-proto-1.0.1" = {
      name = "has-proto";
      packageName = "has-proto";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-proto/-/has-proto-1.0.1.tgz";
        sha512 = "7qE+iP+O+bgF9clE5+UoBFzE65mlBiVj3tKCrlNQ0Ogwm0BjpT/gK4SlLYDMybDh5I3TCTKnPPa0oMG7JDYrhg==";
      };
    };
    "has-symbols-1.0.3" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.3.tgz";
        sha512 = "l3LCuF6MgDNwTDKkdYGEihYjt5pRPbEg46rtlmnSPlUbgmB8LOIrKJbYYFBSbnPaJexMKtiPO8hmeRjRz2Td+A==";
      };
    };
    "has-tostringtag-1.0.0" = {
      name = "has-tostringtag";
      packageName = "has-tostringtag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-tostringtag/-/has-tostringtag-1.0.0.tgz";
        sha512 = "kFjcSNhnlGV1kyoGk7OXKSawH5JOb/LzUc5w9B02hOTO0dfFRjbHQKvg1d6cf3HbeUmtU9VbbV3qzZ2Teh97WQ==";
      };
    };
    "internal-slot-1.0.5" = {
      name = "internal-slot";
      packageName = "internal-slot";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/internal-slot/-/internal-slot-1.0.5.tgz";
        sha512 = "Y+R5hJrzs52QCG2laLn4udYVnxsfny9CpOhNhUvk/SSSVyF6T27FzRbF0sroPidSu3X8oEAkOn2K804mjpt6UQ==";
      };
    };
    "is-arguments-1.1.1" = {
      name = "is-arguments";
      packageName = "is-arguments";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arguments/-/is-arguments-1.1.1.tgz";
        sha512 = "8Q7EARjzEnKpt/PCD7e1cgUS0a6X8u5tdSiMqXhojOdoV9TsMsiO+9VLC5vAmO8N7/GmXn7yjR8qnA6bVAEzfA==";
      };
    };
    "is-bigint-1.0.4" = {
      name = "is-bigint";
      packageName = "is-bigint";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-bigint/-/is-bigint-1.0.4.tgz";
        sha512 = "zB9CruMamjym81i2JZ3UMn54PKGsQzsJeo6xvN3HJJ4CAsQNB6iRutp2To77OfCNuoxspsIhzaPoO1zyCEhFOg==";
      };
    };
    "is-boolean-object-1.1.2" = {
      name = "is-boolean-object";
      packageName = "is-boolean-object";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-boolean-object/-/is-boolean-object-1.1.2.tgz";
        sha512 = "gDYaKHJmnj4aWxyj6YHyXVpdQawtVLHU5cb+eztPGczf6cjuTdwve5ZIEfgXqH4e57An1D1AKf8CZ3kYrQRqYA==";
      };
    };
    "is-callable-1.2.7" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.2.7.tgz";
        sha512 = "1BC0BVFhS/p0qtw6enp8e+8OD0UrK0oFLztSjNzhcKA3WDuJxxAPXzPuPtKkjEY9UUoEWlX/8fgKeu2S8i9JTA==";
      };
    };
    "is-date-object-1.0.5" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.5.tgz";
        sha512 = "9YQaSxsAiSwcvS33MBk3wTCVnWK+HhF8VZR2jRxehM16QcVOdHqPn4VPHmRK4lSr38n9JriurInLcP90xsYNfQ==";
      };
    };
    "is-map-2.0.2" = {
      name = "is-map";
      packageName = "is-map";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-map/-/is-map-2.0.2.tgz";
        sha512 = "cOZFQQozTha1f4MxLFzlgKYPTyj26picdZTx82hbc/Xf4K/tZOOXSCkMvU4pKioRXGDLJRn0GM7Upe7kR721yg==";
      };
    };
    "is-number-object-1.0.7" = {
      name = "is-number-object";
      packageName = "is-number-object";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number-object/-/is-number-object-1.0.7.tgz";
        sha512 = "k1U0IRzLMo7ZlYIfzRu23Oh6MiIFasgpb9X76eqfFZAqwH44UI4KTBvBYIZ1dSL9ZzChTB9ShHfLkR4pdW5krQ==";
      };
    };
    "is-regex-1.1.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.4.tgz";
        sha512 = "kvRdxDsxZjhzUX07ZnLydzS1TU/TJlTUHHY4YLL87e37oUA49DfkLqgy+VjFocowy29cKvcSiu+kIv728jTTVg==";
      };
    };
    "is-set-2.0.2" = {
      name = "is-set";
      packageName = "is-set";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-set/-/is-set-2.0.2.tgz";
        sha512 = "+2cnTEZeY5z/iXGbLhPrOAaK/Mau5k5eXq9j14CpRTftq0pAJu2MwVRSZhyZWBzx3o6X795Lz6Bpb6R0GKf37g==";
      };
    };
    "is-string-1.0.7" = {
      name = "is-string";
      packageName = "is-string";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-string/-/is-string-1.0.7.tgz";
        sha512 = "tE2UXzivje6ofPW7l23cjDOMa09gb7xlAqG6jG5ej6uPV32TlWP3NKPigtaGeHNu9fohccRYvIiZMfOOnOYUtg==";
      };
    };
    "is-symbol-1.0.4" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.4.tgz";
        sha512 = "C/CPBqKWnvdcxqIARxyOh4v1UUEOCHpgDa0WYgpKDFMszcrPcffg5uhwSgPCLD2WWxmq6isisz87tzT01tuGhg==";
      };
    };
    "is-typed-array-1.1.10" = {
      name = "is-typed-array";
      packageName = "is-typed-array";
      version = "1.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typed-array/-/is-typed-array-1.1.10.tgz";
        sha512 = "PJqgEHiWZvMpaFZ3uTc8kHPM4+4ADTlDniuQL7cU/UDA0Ql7F70yGfHph3cLNe+c9toaigv+DFzTJKhc2CtO6A==";
      };
    };
    "is-weakmap-2.0.1" = {
      name = "is-weakmap";
      packageName = "is-weakmap";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-weakmap/-/is-weakmap-2.0.1.tgz";
        sha512 = "NSBR4kH5oVj1Uwvv970ruUkCV7O1mzgVFO4/rev2cLRda9Tm9HrL70ZPut4rOHgY0FNrUu9BCbXA2sdQ+x0chA==";
      };
    };
    "is-weakset-2.0.2" = {
      name = "is-weakset";
      packageName = "is-weakset";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-weakset/-/is-weakset-2.0.2.tgz";
        sha512 = "t2yVvttHkQktwnNNmBQ98AhENLdPUTDTE21uPqAQ0ARwQfGeQKRVS0NNurH7bTf7RrvcVn1OOge45CnBeHCSmg==";
      };
    };
    "isarray-2.0.5" = {
      name = "isarray";
      packageName = "isarray";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-2.0.5.tgz";
        sha512 = "xHjhDr3cNBK0BzdUJSPXZntQUx/mwMS5Rw4A7lPJ90XGAO6ISP/ePDNuo0vhqOZU+UD5JoodwCAAoZQd3FeAKw==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "object-inspect-1.12.3" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.12.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.12.3.tgz";
        sha512 = "geUvdk7c+eizMNUDkRpW1wJwgfOiOeHbxBR/hLXK1aT6zmVSO0jsQcs7fj6MGw89jC/cjGfLcNOrtMYtGqm81g==";
      };
    };
    "object-is-1.1.5" = {
      name = "object-is";
      packageName = "object-is";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-is/-/object-is-1.1.5.tgz";
        sha512 = "3cyDsyHgtmi7I7DfSSI2LDp6SK2lwvtbg0p0R1e0RvTqF5ceGx+K2dfSjm1bKDMVCFEDAQvy+o8c6a7VujOddw==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.assign-4.1.4" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.4.tgz";
        sha512 = "1mxKf0e58bvyjSCtKYY4sRe9itRk3PJpquJOjeIkz885CczcI4IvJJDLPS72oowuSh+pBxUFROpX+TU++hxhZQ==";
      };
    };
    "prop-types-15.8.1" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.8.1.tgz";
        sha512 = "oj87CgZICdulUohogVAR7AjlC0327U4el4L6eAvOqCeudMDVU0NThNaV+b9Df4dXgSP1gXMTnPdhfe/2qDH5cg==";
      };
    };
    "react-18.2.0" = {
      name = "react";
      packageName = "react";
      version = "18.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-18.2.0.tgz";
        sha512 = "/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGQ==";
      };
    };
    "react-dom-18.2.0" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "18.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-18.2.0.tgz";
        sha512 = "6IMTriUmvsjHUjNtEDudZfuDQUoWXVxKHhlEGSk81n4YFS+r/Kl99wXiwlVXtPBtJenozv2P+hxDsw9eA7Xo6g==";
      };
    };
    "react-dropzone-14.2.3" = {
      name = "react-dropzone";
      packageName = "react-dropzone";
      version = "14.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dropzone/-/react-dropzone-14.2.3.tgz";
        sha512 = "O3om8I+PkFKbxCukfIR3QAGftYXDZfOE2N1mr/7qebQJHs7U+/RSL/9xomJNpRg9kM5h9soQSdf0Gc7OHF5Fug==";
      };
    };
    "react-is-16.13.1" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz";
        sha512 = "24e6ynE2H+OKt4kqsOvNd8kBpV65zoxbA4BVsEOB3ARVWQki/DHzaUoC5KuON/BiccDaCCTZBuOcfZs70kR8bQ==";
      };
    };
    "redux-4.1.2" = {
      name = "redux";
      packageName = "redux";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux/-/redux-4.1.2.tgz";
        sha512 = "SH8PglcebESbd/shgf6mii6EIoRM0zrQyjcuQ+ojmfxjTtE0z9Y8pa62iA/OJ58qjP6j27uyW4kUF4jl/jd6sw==";
      };
    };
    "redux-thunk-2.4.2" = {
      name = "redux-thunk";
      packageName = "redux-thunk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/redux-thunk/-/redux-thunk-2.4.2.tgz";
        sha512 = "+P3TjtnP0k/FEjcBL5FZpoovtvrTNT/UXd4/sluaSyrURlSlhLSzEdfsTBW7WsKB6yPvgd7q/iZPICFjW4o57Q==";
      };
    };
    "regenerator-runtime-0.13.11" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.11.tgz";
        sha512 = "kY1AZVr2Ra+t+piVaJ4gxaFaReZVH40AKNo7UCX6W+dEwBo/2oZJzqfuN1qLq1oL45o56cPaTXELwrTh8Fpggg==";
      };
    };
    "regexp.prototype.flags-1.5.0" = {
      name = "regexp.prototype.flags";
      packageName = "regexp.prototype.flags";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexp.prototype.flags/-/regexp.prototype.flags-1.5.0.tgz";
        sha512 = "0SutC3pNudRKgquxGoRGIz946MZVHqbNfPjBdxeOhBrdgDKlRoXmYLQN9xRbrR09ZXWeGAdPuif7egofn6v5LA==";
      };
    };
    "scheduler-0.23.0" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.23.0.tgz";
        sha512 = "CtuThmgHNg7zIZWAXi3AsyIzA3n4xx7aNyjwC2VJldO2LMVDhFK+63xGqq6CsJH4rTAt6/M+N4GhZiDYPx9eUw==";
      };
    };
    "side-channel-1.0.4" = {
      name = "side-channel";
      packageName = "side-channel";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/side-channel/-/side-channel-1.0.4.tgz";
        sha512 = "q5XPytqFEIKHkGdiMIrY10mvLRvnQh42/+GoBlFW3b2LXLE2xxJpZFdm94we0BaoV3RwJyGqg5wS7epxTv0Zvw==";
      };
    };
    "stop-iteration-iterator-1.0.0" = {
      name = "stop-iteration-iterator";
      packageName = "stop-iteration-iterator";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stop-iteration-iterator/-/stop-iteration-iterator-1.0.0.tgz";
        sha512 = "iCGQj+0l0HOdZ2AEeBADlsRC+vsnDsZsbdSiH1yNSjcfKM7fdpCMfqAL/dwF5BLiw/XhRft/Wax6zQbhq2BcjQ==";
      };
    };
    "tabbable-6.1.2" = {
      name = "tabbable";
      packageName = "tabbable";
      version = "6.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tabbable/-/tabbable-6.1.2.tgz";
        sha512 = "qCN98uP7i9z0fIS4amQ5zbGBOq+OSigYeGvPy7NDk8Y9yncqDZ9pRPgfsc2PJIVM9RrJj7GIfuRgmjoUU9zTHQ==";
      };
    };
    "throttle-debounce-3.0.1" = {
      name = "throttle-debounce";
      packageName = "throttle-debounce";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/throttle-debounce/-/throttle-debounce-3.0.1.tgz";
        sha512 = "dTEWWNu6JmeVXY0ZYoPuH5cRIwc0MeGbJwah9KUNYSJwommQpCzTySTpEe8Gs1J23aeWEuAobe4Ag7EHVt/LOg==";
      };
    };
    "tslib-2.5.3" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.5.3.tgz";
        sha512 = "mSxlJJwl3BMEQCUNnxXBU9jP4JBktcEGhURcPR6VQVlnP0FdDEsIaz0C35dXNGLyRfrATNofF0F5p2KPxQgB+w==";
      };
    };
    "which-boxed-primitive-1.0.2" = {
      name = "which-boxed-primitive";
      packageName = "which-boxed-primitive";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-boxed-primitive/-/which-boxed-primitive-1.0.2.tgz";
        sha512 = "bwZdv0AKLpplFY2KZRX6TvyuN7ojjr7lwkg6ml0roIy9YeuSr7JS372qlNW18UQYzgYK9ziGcerWqZOmEn9VNg==";
      };
    };
    "which-collection-1.0.1" = {
      name = "which-collection";
      packageName = "which-collection";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-collection/-/which-collection-1.0.1.tgz";
        sha512 = "W8xeTUwaln8i3K/cY1nGXzdnVZlidBcagyNFtBdD5kxnb4TvGKR7FfSIS3mYpwWS1QUCutfKz8IY8RjftB0+1A==";
      };
    };
    "which-typed-array-1.1.9" = {
      name = "which-typed-array";
      packageName = "which-typed-array";
      version = "1.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-typed-array/-/which-typed-array-1.1.9.tgz";
        sha512 = "w9c4xkx6mPidwp7180ckYWfMmvxpjlZuIudNtDf4N/tTAUB8VJbX25qZoAsrtGuYNnGw3pa0AXgbGKRB8/EceA==";
      };
    };
    "xterm-4.19.0" = {
      name = "xterm";
      packageName = "xterm";
      version = "4.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xterm/-/xterm-4.19.0.tgz";
        sha512 = "c3Cp4eOVsYY5Q839dR5IejghRPpxciGmLWWaP9g+ppfMeBChMeLa1DCA+pmX/jyDZ+zxFOmlJL/82qVdayVoGQ==";
      };
    };
    "xterm-5.1.0" = {
      name = "xterm";
      packageName = "xterm";
      version = "5.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xterm/-/xterm-5.1.0.tgz";
        sha512 = "LovENH4WDzpwynj+OTkLyZgJPeDom9Gra4DMlGAgz6pZhIDCQ+YuO7yfwanY+gVbn/mmZIStNOnVRU/ikQuAEQ==";
      };
    };
    "xterm-addon-canvas-0.3.0" = {
      name = "xterm-addon-canvas";
      packageName = "xterm-addon-canvas";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xterm-addon-canvas/-/xterm-addon-canvas-0.3.0.tgz";
        sha512 = "2deF4ev6T+NjgSM56H+jcAWz4k5viEoaBtuDEyfo5Qdh1r7HOvNzLC45HSeegdH38qmEcL9XIt0KXyOINpSFRA==";
      };
    };
    "xterm-addon-fit-0.2.1" = {
      name = "xterm-addon-fit";
      packageName = "xterm-addon-fit";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xterm-addon-fit/-/xterm-addon-fit-0.2.1.tgz";
        sha512 = "BlR57O3t1/bmVcnS81bn9ZnNf+GiGNbeXdNUKSBa9tKEwNUMcU3S+KFLIRv7rm1Ty0D5pMOu0vbz/RDorKRwKQ==";
      };
    };
  };
  args = {
    name = "machines";
    packageName = "machines";
    src = ./.;
    dependencies = [
      sources."@babel/runtime-7.22.5"
      sources."@novnc/novnc-1.4.0"
      sources."@patternfly/patternfly-5.0.0-alpha.43"
      (sources."@patternfly/react-console-5.0.0-alpha.2" // {
        dependencies = [
          sources."@patternfly/react-core-5.0.0-prerelease.7"
          sources."@patternfly/react-icons-5.0.0-prerelease.7"
          sources."@patternfly/react-styles-5.0.0-prerelease.2"
          sources."xterm-4.19.0"
        ];
      })
      (sources."@patternfly/react-core-5.0.0-alpha.83" // {
        dependencies = [
          sources."focus-trap-7.4.0"
        ];
      })
      sources."@patternfly/react-icons-5.0.0-alpha.12"
      sources."@patternfly/react-styles-5.0.0-alpha.8"
      sources."@patternfly/react-table-5.0.0-alpha.85"
      sources."@patternfly/react-tokens-5.0.0-prerelease.5"
      sources."@spice-project/spice-html5-0.2.1"
      sources."attr-accept-2.2.2"
      sources."available-typed-arrays-1.0.5"
      sources."call-bind-1.0.2"
      sources."date-fns-2.28.0"
      sources."deep-equal-2.0.5"
      sources."define-properties-1.2.0"
      sources."es-get-iterator-1.1.3"
      sources."file-saver-1.3.8"
      sources."file-selector-0.6.0"
      sources."focus-trap-7.4.3"
      sources."for-each-0.3.3"
      sources."function-bind-1.1.1"
      sources."functions-have-names-1.2.3"
      sources."get-intrinsic-1.2.1"
      sources."gopd-1.0.1"
      sources."has-1.0.3"
      sources."has-bigints-1.0.2"
      sources."has-property-descriptors-1.0.0"
      sources."has-proto-1.0.1"
      sources."has-symbols-1.0.3"
      sources."has-tostringtag-1.0.0"
      sources."internal-slot-1.0.5"
      sources."is-arguments-1.1.1"
      sources."is-bigint-1.0.4"
      sources."is-boolean-object-1.1.2"
      sources."is-callable-1.2.7"
      sources."is-date-object-1.0.5"
      sources."is-map-2.0.2"
      sources."is-number-object-1.0.7"
      sources."is-regex-1.1.4"
      sources."is-set-2.0.2"
      sources."is-string-1.0.7"
      sources."is-symbol-1.0.4"
      sources."is-typed-array-1.1.10"
      sources."is-weakmap-2.0.1"
      sources."is-weakset-2.0.2"
      sources."isarray-2.0.5"
      sources."js-tokens-4.0.0"
      sources."lodash-4.17.21"
      sources."loose-envify-1.4.0"
      sources."object-assign-4.1.1"
      sources."object-inspect-1.12.3"
      sources."object-is-1.1.5"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.4"
      sources."prop-types-15.8.1"
      sources."react-18.2.0"
      sources."react-dom-18.2.0"
      sources."react-dropzone-14.2.3"
      sources."react-is-16.13.1"
      sources."redux-4.1.2"
      sources."redux-thunk-2.4.2"
      sources."regenerator-runtime-0.13.11"
      sources."regexp.prototype.flags-1.5.0"
      sources."scheduler-0.23.0"
      sources."side-channel-1.0.4"
      sources."stop-iteration-iterator-1.0.0"
      sources."tabbable-6.1.2"
      sources."throttle-debounce-3.0.1"
      sources."tslib-2.5.3"
      sources."which-boxed-primitive-1.0.2"
      sources."which-collection-1.0.1"
      sources."which-typed-array-1.1.9"
      sources."xterm-5.1.0"
      sources."xterm-addon-canvas-0.3.0"
      (sources."xterm-addon-fit-0.2.1" // {
        dependencies = [
          sources."xterm-4.19.0"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Cockpit UI for virtual machines";
      license = "LGPL-2.1";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
